name: HealME
main: HealME\Main
author: ItzBulkDev
version: 1.0.0
api: [1.12.0]
description: Heals Players on command!
commands:
  heal:
    description: Heals a player or yourself!
    usage: /heal or /heal <player>
